### ISSUE TITLE
multi-user environment

### ISSUE THREAD

**Issue by 98sean98** [sdhnt/open-pos#62]
**Implementation:**
`sub-account` subcollection shall contain documents corresponding to each sub account user. each document capable of storing information specific to each user. on login, the main `user` document is loaded into memory; `subAccount` value is used to store the `sub-account` document into memory, a `isSubAccount` boolean value (default to `false`) is used to indicate the user status for ui rendering. each transaction starts storing a `creator` field:
```
id: // sub-account document id
name:
// other more important information for rendering purposes only
```
not sure if each `product` should have this `creator` field as well, but it doesn’t seem necessary to me

thing to work on:
- decide on a login method before proceeding

**Comment by sdhnt** [comment]
Issue Resolved!
